name: k6 Load Test

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: pageLoadTest.js
            
      - name: Upload Playwright report
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: home_1_vu_PageLoad
          path: home_1_vu_PageLoad
          retention-days: 3
